### ISSUE TITLE
`azd up` went wrong when choosing existing apic resource

### ISSUE THREAD

**Issue by dotnet-7** [Azure/APICenter-Analyzer#13]
**Describe the issue:**

Run `azd up` and select an existing api-center resource, the provision process fails as below:
![image](https://github.com/Azure/APICenter-Analyzer/assets/57525824/e019a579-168b-4c5d-99f3-0e5bb6489fba)

**Repro Steps:**

1. Run `git clone https://github.com/Azure/APICenter-Analyzer.git`
2. Run `cd APICenter-Analyzer`
3. Run `azd up` and input the name and resource group of an existing apicenter

**Environments:**

- azd version: 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)
- os: windows

**Suggestion:**

Update the output of `APIC_NAME` in main.bicep to `output APIC_NAME string = createAPIC ? apiCenter.outputs.id : apiCenterName`

@justinyoo, @hemarina for notification.

**Comment by justinyoo** [comment]
@dotnet-7 Thanks for the finding! Let me double check on my end.

**Comment by justinyoo** [comment]
@dotnet-7 I wasn't able to reproduce the error. Would you please double check whether the APIC instance named `apicenter` exists under the same subscription?

**Comment by justinyoo** [comment]
@dotnet-7 Apart from that error, your bicep change request is valid. I'll update it.
