### ISSUE TITLE
Bug: API Definition is Analyzer is not in pretty format,

### ISSUE THREAD

**Issue by UniperMaster** [Azure/APICenter-Analyzer#7]
if the API is import via the az apic register cli the format in the Analyzer is not in pretty format making it impossible to view errors , if upload the same definition via the portal its fine.

![Screenshot 2024-04-03 133600](https://github.com/Azure/APICenter-Analyzer/assets/58111142/0bbe85e2-ba02-477d-a93b-43178f46a6ba)

**Comment by pierceboggan** [comment]
@UniperMaster Thanks for reporting this! We definitely want to make sure the formatting is retained on import.

When you imported via CLI, I assume you referenced a local file to import the API specification?

**Comment by UniperMaster** [comment]
Yes that was the case.

**Comment by pierceboggan** [comment]
@UniperMaster Awesome, thanks for the details! This is fixed in our next Azure CLI release. I'll update this work item once the fix has been released.

**Comment by UniperMaster** [comment]
Look forward to the update

**Comment by pierceboggan** [comment]
@UniperMaster - This CLI release is now out that contains the bug fix! After running `az upgrade`, run `az -v` and ensure` apic-extension` is at least version `1.0.0b5`. If you're still experiencing this issue with APIs registered with this version, please reopen this issue and let us know. Thanks!

**Comment by UniperMaster** [comment]
@pierceboggan That looks better, Thank you for the update
